name: Testing

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022]
        python-version: [3.9]
        torch-version: [2.7.0, 2.8.0]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}
        run: |
          pip install torch==${{ matrix.torch-version }} --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Install torch-scatter
        run: |
          pip install torch-scatter -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html

      - name: Install METIS
        if: ${{ runner.os != 'Windows' }}
        run: |
          bash .github/workflows/metis.sh
          echo WITH_METIS=1 >> $GITHUB_ENV

      - name: Install METIS on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          bash .github/workflows/metis-${{ runner.os }}.sh
          echo WITH_METIS=0 >> $GITHUB_ENV

      - name: Install scipy
        if: ${{ matrix.python-version == '3.9' }}
        run: |
          pip install scipy==1.10.1

      - name: Install main package
        run: |
          python setup.py develop
        env:
          WITH_METIS: ${{ env.WITH_METIS }}

      - name: Run test-suite
        run: |
          pip install pytest pytest-cov
          pytest --cov --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: success()
        with:
          fail_ci_if_error: false
